### ISSUE TITLE
Web UI validator import returns 500 internal server error if keystore-m password is wrong 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm-web-ui#136]
Reported by @yorickdowne

# 🐞 Bug Report

### Description

Prysm 1.1.0 with Web UI and using the UI to create a wallet and import a keystore-m, on Ubuntu 20.04

If the password for the keystore-m is incorrect, Prysm Web UI will display an error 500 internal server error, but not inform the
user that the password for the keystore-m was incorrect. The wallet is created, just without keys.

Expected behavior: Prysm Web UI prompts user that the password for keystore-m is wrong, the way CLI import does.

**Comment by SeanRobb** [comment]
I believe I am seeing the same issue. I am seeing a 500 error with the message of: "could not read keystore password: inappropriate ioctl for device"

Is that the message you are seeing?

**Comment by ikomorff** [comment]
I have the same problem with the 500 error message and am a bit nervous whether my deposits are now lost. There is no way I am using the wrong password for the keystore file. I created the keystore file with the prysm labs key generator in avado i7. After creating the keystore file, the key generator automatically merged all the information into a folder that can be saved. In the folder is a text file with the mnemonic key and another text file with the keystore password. So it is impossible that I use a wrong password because I use exactly the one from the text file that the key generator has created. Is it really just a bug that can be fixed? Is it possible to create a new keystore file with a new password, as I have the mnemonic key?

**Comment by SeanRobb** [comment]
I ran in to a similar 500's issue with my Avado i5. I removed the package and re-added. During the new on boarding I ensure the wallet password (the last password entered) followed the password guidelines on the Avado launch page. 1 special char, 1 capital and lowercase char and no repeating characters. In my original password I had a repeating char. Updating that password solved my error.

**Comment by ikomorff** [comment]
I have now proceeded step by step:

1. remove volumes
2. remove -> remove dnp + data
3. reinstal validator
4. open validator
5. click i agree
6. create wallet -> imported wallet
7. browse files -> keystore....json
8. continue
9. unlock keystore -> the password I wrote down when I created the wallet and which matches the one in the text file in the validator_keys.tar.gz folder
10. web ui password consisting of 1 uppercase letter, lowercase letters that do not repeat, 1 number and 1 special character
11. third password see 10.
12. error message 500

**Comment by SeanRobb** [comment]
When you go in to inspect element what is the error message you are getting back on your 500?

**Comment by ikomorff** [comment]
![Uploading 0DE660F0-97C5-4605-89E7-336BAF9409C6.jpeg…]()

**Comment by ikomorff** [comment]
Morning,

very good news from the prysm labs support,

 „Hi <@!619885720990908426> , we received your email and will be able to resolve your issue this Monday. apologies for the delay rest assured that if you have your mnemonic, we will get your issue fixed on time Hope that is OK, thanks for your understanding I will get back to you first thing then.“

contact@prysmaticlabs.com and prysmatic labs on discord (rauljordan) can be helpful for anyone who has the same problem.
