### ISSUE TITLE
Show full error message on error pop-up

### ISSUE THREAD

**Issue by dapplion** [prysmaticlabs/prysm-web-ui#99]
Users are reporting errors and they only share the main screen capture with has no information

![1dbaf59cfee6d6d1f83f1869174f2332](https://user-images.githubusercontent.com/35266934/100162489-ae179b00-2eab-11eb-8bd1-844f3bf882ae.png)

They have to open the console to know what's going on 

![unknown](https://user-images.githubusercontent.com/35266934/100162589-def7d000-2eab-11eb-911c-b2e4cdcbadf4.png)

The UI should parse the full error message and show it front and center with as much debugging info as possible until the UI is very stable

**Comment by adidasboy517** [comment]
here is my browser console error log. I even made a third keystore (carefully typing and retyping and remembering the keystore pw) and uploaded the deposit file to the launchpad and sent 32 goeth to the contract: [https://goerli.etherscan.io/tx/0x849d0fa9ca69a06e26840900711b06a026fabed9172007a84973ed577e4041c5]
![Screen Shot 2020-11-24 at 6 41 37 PM](https://user-images.githubusercontent.com/60804080/100167747-582ffc80-2e85-11eb-911f-84a477aeb1e2.png)

**Comment by adidasboy517** [comment]
The issue seems to be the webui password (middle pw step between the keystore pw and the wallet password): it needs to be sufficiently complex. I've found that a min of 7 letters (at least 1 uppercase), min of 3 numbers, and 1 special character works. Going down to 6 letters or 2 numbers (sometimes) doesn't seem to work. Hope this helps. I suggest that the min requirements displayed for the WebUI password be updated to reflect this prior to closing this issue.

**Comment by sedamil** [comment]
Hi all, having a problem as well. Hope similar to dapplion, hopefully its a password issue, pasted my output just in case it provides any more insight. thanks for your hard work!
![WebUI_part1](https://user-images.githubusercontent.com/75135607/100470968-df0bf180-309e-11eb-8078-f4720ac56462.JPG)
![WebUI_part2](https://user-images.githubusercontent.com/75135607/100470980-e3380f00-309e-11eb-8f8c-0ce39688ae3e.JPG)
